name: Cron Bump aws-cli-v2 Version

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force build even if versions are the same'
        required: false
        default: 'true'
        type: boolean
      custom_tag_suffix:
        description: 'Custom DNX tag suffix (e.g., dnx2, dnx3).'
        required: false
        default: 'dnx1'
        type: string

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies and run job
      run: |
        cd .github/automation
        pip install -r requirements.txt
        python main.py
      env:
        GITHUB_TOKEN: ${{secrets.DNX_GITHUB_TOKEN}}
        FORCE_BUILD: ${{ github.event.inputs.force_build || 'false' }}
        CUSTOM_TAG_SUFFIX: ${{ github.event.inputs.custom_tag_suffix || '' }}
